#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 28 12:14:38 2019

@author: mehdi
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt



video =cv2.VideoCapture(0)
